version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - app
    env_file:
      - .env.test
    volumes:
      - ./test/e2e:/usr/src/app/test/e2e