import 'reflect-metadata';
import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import { initializeDatabase } from '@/infrastructure/shared/databaseInitialization';
import { Provider } from '@/presentation/shared/components/ui/provider';

// Force dynamic rendering to prevent static generation during build
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

async function getWebsiteName(): Promise<string> {
  // Only fetch during runtime, not during build
  if (process.env.NEXT_PHASE === 'phase-production-build') {
    return 'Shower'; // Default during build
  }

  try {
    const baseUrl = process.env.SHOWER_URL || 'http://localhost:3000';

    const response = await fetch(`${baseUrl}/api/settings/name`, {
      cache: 'no-store', // Ensure fresh data
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    return data.name || 'Shower';
  } catch (error) {
    console.error('Failed to fetch website name:', error);
    return 'Shower'; // Default fallback
  }
}

async function getWebsiteIcon(): Promise<string | null> {
  // Only fetch during runtime, not during build
  if (process.env.NEXT_PHASE === 'phase-production-build') {
    return null; // Default during build
  }

  try {
    const baseUrl = process.env.SHOWER_URL || 'http://localhost:3000';

    const response = await fetch(`${baseUrl}/api/settings/icon`, {
      cache: 'no-store', // Ensure fresh data
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    return data.icon?.url || null;
  } catch (error) {
    console.error('Failed to fetch website icon:', error);
    return null; // Default fallback
  }
}

export async function generateMetadata(): Promise<Metadata> {
  const websiteName = await getWebsiteName();
  const websiteIcon = await getWebsiteIcon();

  return {
    title: websiteName,
    description: 'Generated by create next app',
    icons: websiteIcon
      ? {
          icon: websiteIcon,
          shortcut: websiteIcon,
          apple: websiteIcon,
        }
      : undefined,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Initialize database connection
  await initializeDatabase();

  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
